$manifestPath = "manifest.json"
$outputPath = "install_local.lua"

if (-not (Test-Path $manifestPath)) {
    Write-Error "Manifest file not found: $manifestPath"
    exit 1
}

$manifestContent = Get-Content -Raw $manifestPath
$manifest = $manifestContent | ConvertFrom-Json

$output = @()
$output += "--[[ Local Installer generated by bundle.ps1 ]]"
$output += "local files = {}"
$output += ""

foreach ($file in $manifest.files) {
    $path = $file.path
    if (Test-Path $path) {
        $content = Get-Content -Raw $path
        # Escape backslashes and double quotes for Lua string
        # We use a long string with a unique delimiter to avoid conflicts
        $delimiter = "EOF" + (Get-Random)
        
        $output += "files['$path'] = [[$content]]"
    } else {
        Write-Warning "File not found: $path"
    }
}

# Add manifest.json itself
$output += "files['manifest.json'] = [[$manifestContent]]"

$output += ""
$output += "-- Installer Logic"
$output += "print('Installing files...')"
$output += "for path, content in pairs(files) do"
$output += "    local dir = fs.getDir(path)"
$output += "    if not fs.exists(dir) then"
$output += "        fs.makeDir(dir)"
$output += "    end"
$output += "    local f = fs.open(path, 'w')"
$output += "    f.write(content)"
$output += "    f.close()"
$output += "    print('Installed: ' .. path)"
$output += "end"
$output += "print('Installation complete. Rebooting in 3 seconds...')"
$output += "sleep(3)"
$output += "os.reboot()"

$output | Set-Content -Path $outputPath
Write-Host "Generated $outputPath"
