-- installer.lua
-- Arcadesys Unified Installer
-- Detects platform (Turtle vs Computer) and installs appropriate components.

local function clear()
    term.clear()
    term.setCursorPos(1,1)
end

local function printHeader()
    clear()
    print("========================================")
    print("       ARCADESYS UNIFIED INSTALLER      ")
    print("========================================")
    print("")
end

local function detectPlatform()
    if turtle then
        return "turtle"
    else
        return "computer"
    end
end

local function install()
    printHeader()
    local platform = detectPlatform()
    print("Detected Platform: " .. string.upper(platform))
    print("")
    
    print("This installer would normally download files from a server.")
    print("Since you are running from a local repo, the files are already here.")
    print("")
    print("Verifying structure...")
    
    local missing = false
    if not fs.exists("lib") then print("! Missing /lib"); missing = true end
    if not fs.exists("arcade") then print("! Missing /arcade"); missing = true end
    if not fs.exists("factory") then print("! Missing /factory"); missing = true end
    
    if missing then
        print("")
        print("Error: Repository structure is incomplete.")
        return
    end
    
    print("Structure OK.")
    print("")
    
    print("Creating startup.lua...")
    local startupContent = [[
-- startup.lua
-- Auto-generated by Arcadesys Installer

local platform = turtle and "turtle" or "computer"

-- Add lib and arcade to package path
package.path = package.path .. ";/lib/?.lua;/arcade/?.lua;/factory/?.lua"

if platform == "turtle" then
    if fs.exists("/factory/factory.lua") then
        shell.run("/factory/factory.lua")
    else
        print("Factory agent not found.")
    end
else
    if fs.exists("/arcade/arcade_shell.lua") then
        shell.run("/arcade/arcade_shell.lua")
    else
        print("ArcadeOS not found.")
    end
end
]]

    local h = fs.open("startup.lua", "w")
    h.write(startupContent)
    h.close()
    
    print("startup.lua created.")
    print("")
    print("Installation Complete!")
    print("Rebooting in 3 seconds...")
    os.sleep(3)
    os.reboot()
end

install()
