-- startup.lua
-- Auto-generated by Arcadesys Installer

local platform = turtle and "turtle" or "computer"

-- Add lib and arcade to package path
package.path = package.path .. ";/lib/?.lua;/arcade/?.lua;/factory/?.lua"

if platform == "turtle" then
    local turtle_os = "/factory/turtle_os.lua"

    if fs.exists(turtle_os) then
        shell.run(turtle_os)
    else
        print("Factory TurtleOS not found at " .. turtle_os)
    end
else
    local arcade_os = "/arcade/arcadeos.lua"

    if fs.exists(arcade_os) then
        shell.run(arcade_os)
    else
        print("ArcadeOS not found at " .. arcade_os)
    end
end
