---@diagnostic disable: undefined-global, undefined-field, param-type-mismatch

-- startup.lua
-- Auto-generated by Arcadesys Installer

local EXPERIENCE_FILE = "experience.settings"
local DEFAULT_COMPUTER_EXPERIENCE = "workstation"

local platform = turtle and "turtle" or "computer"

local function loadExperience()
    if platform == "turtle" then
        return "turtle"
    end

    if not fs.exists(EXPERIENCE_FILE) then
        return DEFAULT_COMPUTER_EXPERIENCE
    end

    local ok, data = pcall(function()
        local handle = fs.open(EXPERIENCE_FILE, "r")
        if not handle then
            return nil
        end
        local contents = handle.readAll()
        handle.close()
        return textutils.unserialize(contents)
    end)

    if ok and type(data) == "table" and type(data.experience) == "string" then
        return data.experience
    end

    return DEFAULT_COMPUTER_EXPERIENCE
end

local experience = loadExperience()

-- Add lib and arcade to package path
package.path = package.path .. ";/?.lua;/lib/?.lua;/arcade/?.lua;/factory/?.lua"

local function runProgram(path, label)
    if fs.exists(path) then
        ---@diagnostic disable-next-line: param-type-mismatch
        shell.run(path)
    else
        print(label .. " not found at " .. path)
    end
end

if experience == "turtle" then
    runProgram("/factory/main.lua", "Factory Main")
elseif experience == "arcade" then
    runProgram("/arcade/arcade_arcade.lua", "ArcadeArcade")
else
    runProgram("/arcade/arcade_shell.lua", "Arcade Shell")
end
