-- startup.lua
-- Auto-generated by Arcadesys Installer

local platform = turtle and "turtle" or "computer"

-- Add lib and arcade to package path
package.path = package.path .. ";/lib/?.lua;/arcade/?.lua;/factory/?.lua"

if platform == "turtle" then
    if fs.exists("/factory/factory.lua") then
        shell.run("/factory/factory.lua")
    else
        print("Factory agent not found.")
    end
else
    if fs.exists("/arcade/arcade_shell.lua") then
        shell.run("/arcade/arcade_shell.lua")
    else
        print("ArcadeOS not found.")
    end
end
