local items = {
    { id = "minecraft:stone", name = "Stone", color = colors.lightGray, sym = "#" },
    { id = "minecraft:granite", name = "Granite", color = colors.red, sym = "#" },
    { id = "minecraft:polished_granite", name = "Polished Granite", color = colors.red, sym = "#" },
    { id = "minecraft:diorite", name = "Diorite", color = colors.white, sym = "#" },
    { id = "minecraft:polished_diorite", name = "Polished Diorite", color = colors.white, sym = "#" },
    { id = "minecraft:andesite", name = "Andesite", color = colors.gray, sym = "#" },
    { id = "minecraft:polished_andesite", name = "Polished Andesite", color = colors.gray, sym = "#" },
    { id = "minecraft:grass_block", name = "Grass Block", color = colors.green, sym = "G" },
    { id = "minecraft:dirt", name = "Dirt", color = colors.brown, sym = "d" },
    { id = "minecraft:coarse_dirt", name = "Coarse Dirt", color = colors.brown, sym = "d" },
    { id = "minecraft:podzol", name = "Podzol", color = colors.brown, sym = "d" },
    { id = "minecraft:cobblestone", name = "Cobblestone", color = colors.gray, sym = "C" },
    { id = "minecraft:oak_planks", name = "Oak Planks", color = colors.brown, sym = "P" },
    { id = "minecraft:spruce_planks", name = "Spruce Planks", color = colors.brown, sym = "P" },
    { id = "minecraft:birch_planks", name = "Birch Planks", color = colors.yellow, sym = "P" },
    { id = "minecraft:jungle_planks", name = "Jungle Planks", color = colors.brown, sym = "P" },
    { id = "minecraft:acacia_planks", name = "Acacia Planks", color = colors.orange, sym = "P" },
    { id = "minecraft:dark_oak_planks", name = "Dark Oak Planks", color = colors.brown, sym = "P" },
    { id = "minecraft:mangrove_planks", name = "Mangrove Planks", color = colors.red, sym = "P" },
    { id = "minecraft:cherry_planks", name = "Cherry Planks", color = colors.pink, sym = "P" },
    { id = "minecraft:bamboo_planks", name = "Bamboo Planks", color = colors.yellow, sym = "P" },
    { id = "minecraft:bedrock", name = "Bedrock", color = colors.black, sym = "B" },
    { id = "minecraft:sand", name = "Sand", color = colors.yellow, sym = "s" },
    { id = "minecraft:red_sand", name = "Red Sand", color = colors.orange, sym = "s" },
    { id = "minecraft:gravel", name = "Gravel", color = colors.gray, sym = "g" },
    { id = "minecraft:gold_ore", name = "Gold Ore", color = colors.yellow, sym = "o" },
    { id = "minecraft:iron_ore", name = "Iron Ore", color = colors.brown, sym = "o" },
    { id = "minecraft:coal_ore", name = "Coal Ore", color = colors.black, sym = "o" },
    { id = "minecraft:nether_gold_ore", name = "Nether Gold Ore", color = colors.yellow, sym = "o" },
    { id = "minecraft:oak_log", name = "Oak Log", color = colors.brown, sym = "L" },
    { id = "minecraft:spruce_log", name = "Spruce Log", color = colors.brown, sym = "L" },
    { id = "minecraft:birch_log", name = "Birch Log", color = colors.white, sym = "L" },
    { id = "minecraft:jungle_log", name = "Jungle Log", color = colors.brown, sym = "L" },
    { id = "minecraft:acacia_log", name = "Acacia Log", color = colors.orange, sym = "L" },
    { id = "minecraft:dark_oak_log", name = "Dark Oak Log", color = colors.brown, sym = "L" },
    { id = "minecraft:mangrove_log", name = "Mangrove Log", color = colors.red, sym = "L" },
    { id = "minecraft:cherry_log", name = "Cherry Log", color = colors.pink, sym = "L" },
    { id = "minecraft:stripped_oak_log", name = "Stripped Oak Log", color = colors.brown, sym = "L" },
    { id = "minecraft:stripped_spruce_log", name = "Stripped Spruce Log", color = colors.brown, sym = "L" },
    { id = "minecraft:stripped_birch_log", name = "Stripped Birch Log", color = colors.white, sym = "L" },
    { id = "minecraft:stripped_jungle_log", name = "Stripped Jungle Log", color = colors.brown, sym = "L" },
    { id = "minecraft:stripped_acacia_log", name = "Stripped Acacia Log", color = colors.orange, sym = "L" },
    { id = "minecraft:stripped_dark_oak_log", name = "Stripped Dark Oak Log", color = colors.brown, sym = "L" },
    { id = "minecraft:stripped_mangrove_log", name = "Stripped Mangrove Log", color = colors.red, sym = "L" },
    { id = "minecraft:stripped_cherry_log", name = "Stripped Cherry Log", color = colors.pink, sym = "L" },
    { id = "minecraft:glass", name = "Glass", color = colors.lightBlue, sym = "G" },
    { id = "minecraft:lapis_ore", name = "Lapis Ore", color = colors.blue, sym = "o" },
    { id = "minecraft:diamond_ore", name = "Diamond Ore", color = colors.cyan, sym = "o" },
    { id = "minecraft:redstone_ore", name = "Redstone Ore", color = colors.red, sym = "o" },
    { id = "minecraft:emerald_ore", name = "Emerald Ore", color = colors.green, sym = "o" },
    { id = "minecraft:white_wool", name = "White Wool", color = colors.white, sym = "W" },
    { id = "minecraft:orange_wool", name = "Orange Wool", color = colors.orange, sym = "W" },
    { id = "minecraft:magenta_wool", name = "Magenta Wool", color = colors.magenta, sym = "W" },
    { id = "minecraft:light_blue_wool", name = "Light Blue Wool", color = colors.lightBlue, sym = "W" },
    { id = "minecraft:yellow_wool", name = "Yellow Wool", color = colors.yellow, sym = "W" },
    { id = "minecraft:lime_wool", name = "Lime Wool", color = colors.lime, sym = "W" },
    { id = "minecraft:pink_wool", name = "Pink Wool", color = colors.pink, sym = "W" },
    { id = "minecraft:gray_wool", name = "Gray Wool", color = colors.gray, sym = "W" },
    { id = "minecraft:light_gray_wool", name = "Light Gray Wool", color = colors.lightGray, sym = "W" },
    { id = "minecraft:cyan_wool", name = "Cyan Wool", color = colors.cyan, sym = "W" },
    { id = "minecraft:purple_wool", name = "Purple Wool", color = colors.purple, sym = "W" },
    { id = "minecraft:blue_wool", name = "Blue Wool", color = colors.blue, sym = "W" },
    { id = "minecraft:brown_wool", name = "Brown Wool", color = colors.brown, sym = "W" },
    { id = "minecraft:green_wool", name = "Green Wool", color = colors.green, sym = "W" },
    { id = "minecraft:red_wool", name = "Red Wool", color = colors.red, sym = "W" },
    { id = "minecraft:black_wool", name = "Black Wool", color = colors.black, sym = "W" },
    { id = "minecraft:bricks", name = "Bricks", color = colors.red, sym = "B" },
    { id = "minecraft:bookshelf", name = "Bookshelf", color = colors.brown, sym = "#" },
    { id = "minecraft:mossy_cobblestone", name = "Mossy Cobblestone", color = colors.gray, sym = "C" },
    { id = "minecraft:obsidian", name = "Obsidian", color = colors.black, sym = "O" },
    { id = "minecraft:torch", name = "Torch", color = colors.yellow, sym = "i" },
    { id = "minecraft:chest", name = "Chest", color = colors.brown, sym = "C" },
    { id = "minecraft:crafting_table", name = "Crafting Table", color = colors.brown, sym = "T" },
    { id = "minecraft:furnace", name = "Furnace", color = colors.gray, sym = "F" },
    { id = "minecraft:ladder", name = "Ladder", color = colors.brown, sym = "H" },
    { id = "minecraft:snow", name = "Snow", color = colors.white, sym = "S" },
    { id = "minecraft:ice", name = "Ice", color = colors.lightBlue, sym = "I" },
    { id = "minecraft:snow_block", name = "Snow Block", color = colors.white, sym = "S" },
    { id = "minecraft:clay", name = "Clay", color = colors.lightGray, sym = "C" },
    { id = "minecraft:pumpkin", name = "Pumpkin", color = colors.orange, sym = "P" },
    { id = "minecraft:netherrack", name = "Netherrack", color = colors.red, sym = "N" },
    { id = "minecraft:soul_sand", name = "Soul Sand", color = colors.brown, sym = "S" },
    { id = "minecraft:soul_soil", name = "Soul Soil", color = colors.brown, sym = "S" },
    { id = "minecraft:basalt", name = "Basalt", color = colors.gray, sym = "B" },
    { id = "minecraft:polished_basalt", name = "Polished Basalt", color = colors.gray, sym = "B" },
    { id = "minecraft:glowstone", name = "Glowstone", color = colors.yellow, sym = "G" },
    { id = "minecraft:stone_bricks", name = "Stone Bricks", color = colors.gray, sym = "B" },
    { id = "minecraft:mossy_stone_bricks", name = "Mossy Stone Bricks", color = colors.gray, sym = "B" },
    { id = "minecraft:cracked_stone_bricks", name = "Cracked Stone Bricks", color = colors.gray, sym = "B" },
    { id = "minecraft:chiseled_stone_bricks", name = "Chiseled Stone Bricks", color = colors.gray, sym = "B" },
    { id = "minecraft:deepslate", name = "Deepslate", color = colors.gray, sym = "D" },
    { id = "minecraft:cobbled_deepslate", name = "Cobbled Deepslate", color = colors.gray, sym = "D" },
    { id = "minecraft:polished_deepslate", name = "Polished Deepslate", color = colors.gray, sym = "D" },
    { id = "minecraft:deepslate_bricks", name = "Deepslate Bricks", color = colors.gray, sym = "D" },
    { id = "minecraft:deepslate_tiles", name = "Deepslate Tiles", color = colors.gray, sym = "D" },
    { id = "minecraft:reinforced_deepslate", name = "Reinforced Deepslate", color = colors.black, sym = "D" },
    { id = "minecraft:melon", name = "Melon", color = colors.green, sym = "M" },
    { id = "minecraft:mycelium", name = "Mycelium", color = colors.purple, sym = "M" },
    { id = "minecraft:nether_bricks", name = "Nether Bricks", color = colors.red, sym = "B" },
    { id = "minecraft:end_stone", name = "End Stone", color = colors.yellow, sym = "E" },
    { id = "minecraft:emerald_block", name = "Emerald Block", color = colors.green, sym = "E" },
    { id = "minecraft:quartz_block", name = "Quartz Block", color = colors.white, sym = "Q" },
    { id = "minecraft:white_terracotta", name = "White Terracotta", color = colors.white, sym = "T" },
    { id = "minecraft:orange_terracotta", name = "Orange Terracotta", color = colors.orange, sym = "T" },
    { id = "minecraft:magenta_terracotta", name = "Magenta Terracotta", color = colors.magenta, sym = "T" },
    { id = "minecraft:light_blue_terracotta", name = "Light Blue Terracotta", color = colors.lightBlue, sym = "T" },
    { id = "minecraft:yellow_terracotta", name = "Yellow Terracotta", color = colors.yellow, sym = "T" },
    { id = "minecraft:lime_terracotta", name = "Lime Terracotta", color = colors.lime, sym = "T" },
    { id = "minecraft:pink_terracotta", name = "Pink Terracotta", color = colors.pink, sym = "T" },
    { id = "minecraft:gray_terracotta", name = "Gray Terracotta", color = colors.gray, sym = "T" },
    { id = "minecraft:light_gray_terracotta", name = "Light Gray Terracotta", color = colors.lightGray, sym = "T" },
    { id = "minecraft:cyan_terracotta", name = "Cyan Terracotta", color = colors.cyan, sym = "T" },
    { id = "minecraft:purple_terracotta", name = "Purple Terracotta", color = colors.purple, sym = "T" },
    { id = "minecraft:blue_terracotta", name = "Blue Terracotta", color = colors.blue, sym = "T" },
    { id = "minecraft:brown_terracotta", name = "Brown Terracotta", color = colors.brown, sym = "T" },
    { id = "minecraft:green_terracotta", name = "Green Terracotta", color = colors.green, sym = "T" },
    { id = "minecraft:red_terracotta", name = "Red Terracotta", color = colors.red, sym = "T" },
    { id = "minecraft:black_terracotta", name = "Black Terracotta", color = colors.black, sym = "T" },
    { id = "minecraft:hay_block", name = "Hay Bale", color = colors.yellow, sym = "H" },
    { id = "minecraft:terracotta", name = "Terracotta", color = colors.orange, sym = "T" },
    { id = "minecraft:coal_block", name = "Block of Coal", color = colors.black, sym = "C" },
    { id = "minecraft:packed_ice", name = "Packed Ice", color = colors.lightBlue, sym = "I" },
    { id = "minecraft:blue_ice", name = "Blue Ice", color = colors.blue, sym = "I" },
    { id = "minecraft:prismarine", name = "Prismarine", color = colors.cyan, sym = "P" },
    { id = "minecraft:prismarine_bricks", name = "Prismarine Bricks", color = colors.cyan, sym = "P" },
    { id = "minecraft:dark_prismarine", name = "Dark Prismarine", color = colors.cyan, sym = "P" },
    { id = "minecraft:sea_lantern", name = "Sea Lantern", color = colors.white, sym = "L" },
    { id = "minecraft:red_sandstone", name = "Red Sandstone", color = colors.orange, sym = "S" },
    { id = "minecraft:magma_block", name = "Magma Block", color = colors.red, sym = "M" },
    { id = "minecraft:nether_wart_block", name = "Nether Wart Block", color = colors.red, sym = "W" },
    { id = "minecraft:warped_wart_block", name = "Warped Wart Block", color = colors.cyan, sym = "W" },
    { id = "minecraft:red_nether_bricks", name = "Red Nether Bricks", color = colors.red, sym = "B" },
    { id = "minecraft:bone_block", name = "Bone Block", color = colors.white, sym = "B" },
    { id = "minecraft:shulker_box", name = "Shulker Box", color = colors.purple, sym = "S" },
    { id = "minecraft:white_concrete", name = "White Concrete", color = colors.white, sym = "C" },
    { id = "minecraft:orange_concrete", name = "Orange Concrete", color = colors.orange, sym = "C" },
    { id = "minecraft:magenta_concrete", name = "Magenta Concrete", color = colors.magenta, sym = "C" },
    { id = "minecraft:light_blue_concrete", name = "Light Blue Concrete", color = colors.lightBlue, sym = "C" },
    { id = "minecraft:yellow_concrete", name = "Yellow Concrete", color = colors.yellow, sym = "C" },
    { id = "minecraft:lime_concrete", name = "Lime Concrete", color = colors.lime, sym = "C" },
    { id = "minecraft:pink_concrete", name = "Pink Concrete", color = colors.pink, sym = "C" },
    { id = "minecraft:gray_concrete", name = "Gray Concrete", color = colors.gray, sym = "C" },
    { id = "minecraft:light_gray_concrete", name = "Light Gray Concrete", color = colors.lightGray, sym = "C" },
    { id = "minecraft:cyan_concrete", name = "Cyan Concrete", color = colors.cyan, sym = "C" },
    { id = "minecraft:purple_concrete", name = "Purple Concrete", color = colors.purple, sym = "C" },
    { id = "minecraft:blue_concrete", name = "Blue Concrete", color = colors.blue, sym = "C" },
    { id = "minecraft:brown_concrete", name = "Brown Concrete", color = colors.brown, sym = "C" },
    { id = "minecraft:green_concrete", name = "Green Concrete", color = colors.green, sym = "C" },
    { id = "minecraft:red_concrete", name = "Red Concrete", color = colors.red, sym = "C" },
    { id = "minecraft:black_concrete", name = "Black Concrete", color = colors.black, sym = "C" },
    { id = "minecraft:white_concrete_powder", name = "White Concrete Powder", color = colors.white, sym = "P" },
    { id = "minecraft:orange_concrete_powder", name = "Orange Concrete Powder", color = colors.orange, sym = "P" },
    { id = "minecraft:magenta_concrete_powder", name = "Magenta Concrete Powder", color = colors.magenta, sym = "P" },
    { id = "minecraft:light_blue_concrete_powder", name = "Light Blue Concrete Powder", color = colors.lightBlue, sym = "P" },
    { id = "minecraft:yellow_concrete_powder", name = "Yellow Concrete Powder", color = colors.yellow, sym = "P" },
    { id = "minecraft:lime_concrete_powder", name = "Lime Concrete Powder", color = colors.lime, sym = "P" },
    { id = "minecraft:pink_concrete_powder", name = "Pink Concrete Powder", color = colors.pink, sym = "P" },
    { id = "minecraft:gray_concrete_powder", name = "Gray Concrete Powder", color = colors.gray, sym = "P" },
    { id = "minecraft:light_gray_concrete_powder", name = "Light Gray Concrete Powder", color = colors.lightGray, sym = "P" },
    { id = "minecraft:cyan_concrete_powder", name = "Cyan Concrete Powder", color = colors.cyan, sym = "P" },
    { id = "minecraft:purple_concrete_powder", name = "Purple Concrete Powder", color = colors.purple, sym = "P" },
    { id = "minecraft:blue_concrete_powder", name = "Blue Concrete Powder", color = colors.blue, sym = "P" },
    { id = "minecraft:brown_concrete_powder", name = "Brown Concrete Powder", color = colors.brown, sym = "P" },
    { id = "minecraft:green_concrete_powder", name = "Green Concrete Powder", color = colors.green, sym = "P" },
    { id = "minecraft:red_concrete_powder", name = "Red Concrete Powder", color = colors.red, sym = "P" },
    { id = "minecraft:black_concrete_powder", name = "Black Concrete Powder", color = colors.black, sym = "P" },
    { id = "minecraft:dried_kelp_block", name = "Dried Kelp Block", color = colors.green, sym = "K" },
    { id = "minecraft:dead_tube_coral_block", name = "Dead Tube Coral Block", color = colors.gray, sym = "C" },
    { id = "minecraft:dead_brain_coral_block", name = "Dead Brain Coral Block", color = colors.gray, sym = "C" },
    { id = "minecraft:dead_bubble_coral_block", name = "Dead Bubble Coral Block", color = colors.gray, sym = "C" },
    { id = "minecraft:dead_fire_coral_block", name = "Dead Fire Coral Block", color = colors.gray, sym = "C" },
    { id = "minecraft:dead_horn_coral_block", name = "Dead Horn Coral Block", color = colors.gray, sym = "C" },
    { id = "minecraft:tube_coral_block", name = "Tube Coral Block", color = colors.blue, sym = "C" },
    { id = "minecraft:brain_coral_block", name = "Brain Coral Block", color = colors.pink, sym = "C" },
    { id = "minecraft:bubble_coral_block", name = "Bubble Coral Block", color = colors.magenta, sym = "C" },
    { id = "minecraft:fire_coral_block", name = "Fire Coral Block", color = colors.red, sym = "C" },
    { id = "minecraft:horn_coral_block", name = "Horn Coral Block", color = colors.yellow, sym = "C" },
    { id = "minecraft:honey_block", name = "Honey Block", color = colors.orange, sym = "H" },
    { id = "minecraft:honeycomb_block", name = "Honeycomb Block", color = colors.orange, sym = "H" },
    { id = "minecraft:netherite_block", name = "Block of Netherite", color = colors.black, sym = "N" },
    { id = "minecraft:ancient_debris", name = "Ancient Debris", color = colors.brown, sym = "D" },
    { id = "minecraft:crying_obsidian", name = "Crying Obsidian", color = colors.purple, sym = "O" },
    { id = "minecraft:blackstone", name = "Blackstone", color = colors.black, sym = "B" },
    { id = "minecraft:polished_blackstone", name = "Polished Blackstone", color = colors.black, sym = "B" },
    { id = "minecraft:polished_blackstone_bricks", name = "Polished Blackstone Bricks", color = colors.black, sym = "B" },
    { id = "minecraft:gilded_blackstone", name = "Gilded Blackstone", color = colors.black, sym = "B" },
    { id = "minecraft:chiseled_polished_blackstone", name = "Chiseled Polished Blackstone", color = colors.black, sym = "B" },
    { id = "minecraft:quartz_bricks", name = "Quartz Bricks", color = colors.white, sym = "Q" },
    { id = "minecraft:amethyst_block", name = "Block of Amethyst", color = colors.purple, sym = "A" },
    { id = "minecraft:budding_amethyst", name = "Budding Amethyst", color = colors.purple, sym = "A" },
    { id = "minecraft:tuff", name = "Tuff", color = colors.gray, sym = "T" },
    { id = "minecraft:calcite", name = "Calcite", color = colors.white, sym = "C" },
    { id = "minecraft:tinted_glass", name = "Tinted Glass", color = colors.gray, sym = "G" },
    { id = "minecraft:smooth_basalt", name = "Smooth Basalt", color = colors.gray, sym = "B" },
    { id = "minecraft:raw_iron_block", name = "Block of Raw Iron", color = colors.brown, sym = "I" },
    { id = "minecraft:raw_copper_block", name = "Block of Raw Copper", color = colors.orange, sym = "C" },
    { id = "minecraft:raw_gold_block", name = "Block of Raw Gold", color = colors.yellow, sym = "G" },
    { id = "minecraft:dripstone_block", name = "Dripstone Block", color = colors.brown, sym = "D" },
    { id = "minecraft:moss_block", name = "Moss Block", color = colors.green, sym = "M" },
    { id = "minecraft:mud", name = "Mud", color = colors.brown, sym = "M" },
    { id = "minecraft:packed_mud", name = "Packed Mud", color = colors.brown, sym = "M" },
    { id = "minecraft:mud_bricks", name = "Mud Bricks", color = colors.brown, sym = "M" },
    { id = "minecraft:sculk", name = "Sculk", color = colors.cyan, sym = "S" },
    { id = "minecraft:sculk_catalyst", name = "Sculk Catalyst", color = colors.cyan, sym = "S" },
    { id = "minecraft:sculk_shrieker", name = "Sculk Shrieker", color = colors.cyan, sym = "S" },
    { id = "minecraft:ochre_froglight", name = "Ochre Froglight", color = colors.yellow, sym = "F" },
    { id = "minecraft:verdant_froglight", name = "Verdant Froglight", color = colors.green, sym = "F" },
    { id = "minecraft:pearlescent_froglight", name = "Pearlescent Froglight", color = colors.purple, sym = "F" },
}

return items