# Sync the workspace into CraftOS-PC computers for fast local testing.
# - Copies the repo into a subfolder (default: arcadesys) under each target computer ID.
# - Writes a small startup shim so CraftOS-PC boots straight into arcadesys_os.lua.
# - Does not alter the turtle state machine; it only stages files.
param(
    [string]$DataDir = "$env:APPDATA/CraftOS-PC",
    [int]$ComputerId = 0,
    [int]$TurtleId = 1,
    [string]$Subdir = "arcadesys",
    [switch]$SkipComputer,
    [switch]$SkipTurtle
)

$workspaceRoot = Resolve-Path (Join-Path $PSScriptRoot "..")
$computerDir = Join-Path $DataDir "computer"
$configDir = Join-Path $DataDir "config"

$copyList = @(
    "arcadesys_os.lua",
    "startup.lua",
    "arcade",
    "factory",
    "lib",
    "ui",
    "factory_planner.lua",
    "ae2_drive_monitor.lua",
    "ae2_me_bridge_monitor.lua",
    "printer.lua",
    "tools\receive_schema.lua",
    "tools\install_sender.lua",
    "factory\dist\factory.lua"
)

function Ensure-Dir($path) {
    if (-not (Test-Path $path)) {
        New-Item -ItemType Directory -Path $path -Force | Out-Null
    }
}

function Write-StartupShim($targetRoot, $subdir) {
    $startupPath = Join-Path $targetRoot "startup.lua"
    $shim = @"
-- Generated by tools/craftos_sync.ps1
local base = "$subdir"
local entry = fs.combine(base, "arcadesys_os.lua")
if fs.exists(entry) then
    shell.run(entry)
else
    print("Arcadesys entry not found at " .. entry)
end
"@

    if (Test-Path $startupPath) {
        $existing = Get-Content $startupPath -Raw -ErrorAction SilentlyContinue
        if ($existing -ne $shim) {
            Copy-Item $startupPath ($startupPath + ".bak") -Force
        }
    }
    $shim | Set-Content -Encoding ASCII $startupPath
}

function Copy-Workspace($destRoot, $subdir) {
    $dest = Join-Path $destRoot $subdir
    if (Test-Path $dest) {
        Remove-Item -Path $dest -Recurse -Force
    }
    Ensure-Dir $dest

    foreach ($item in $copyList) {
        $src = Join-Path $workspaceRoot $item
        if (-not (Test-Path $src)) {
            continue
        }
        $dst = Join-Path $dest $item
        Ensure-Dir (Split-Path $dst -Parent)
        Copy-Item -Path $src -Destination $dst -Recurse -Force
    }
}

function Sync-Computer($id, $label) {
    $targetRoot = Join-Path $computerDir $id
    Ensure-Dir $targetRoot
    Copy-Workspace $targetRoot $Subdir
    Write-StartupShim $targetRoot $Subdir
    $targetCfg = Join-Path $configDir ("{0}.json" -f $id)
    if (-not (Test-Path $targetCfg)) {
        $template = Join-Path $configDir "0.json"
        if (Test-Path $template) {
            Copy-Item $template $targetCfg
        } else {
            '{"isColor":true}' | Set-Content -Encoding ASCII $targetCfg
        }
    }
    Write-Host ("Synced {0} profile to {1}" -f $label, $targetRoot)
}

Ensure-Dir $computerDir
Ensure-Dir $configDir

if (-not $SkipComputer) {
    Sync-Computer $ComputerId "computer"
}
if (-not $SkipTurtle) {
    Sync-Computer $TurtleId "turtle"
}

Write-Host ""
Write-Host "Done. Open CraftOS-PC with --computers-dir `"$computerDir`" (or point the GUI to that data folder)."
Write-Host "If the turtle profile doesn't expose turtle APIs, create a Turtle with ID $TurtleId in CraftOS-PC first, then re-run this script."
